# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createFisherMat <- function(allocationsPerArm) {
    .Call(`_monteCarloProportions_createFisherMat`, allocationsPerArm)
}

monteCarloFisherR <- function(alloc, outcomes) {
    .Call(`_monteCarloProportions_monteCarloFisherR`, alloc, outcomes)
}

multiTrialTrueFalsePos <- function(baselineRisks, participantsPerArm, absRRStep, monteCarloRuns, path) {
    invisible(.Call(`_monteCarloProportions_multiTrialTrueFalsePos`, baselineRisks, participantsPerArm, absRRStep, monteCarloRuns, path))
}

